name: bloodbank
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.1
  shared_preferences: ^0.5.7+2
  flutter_svg: ^0.17.4
  flutter_datetime_picker: ^1.3.8
  curved_navigation_bar: ^0.3.2
  provider: ^3.0.0+1
#  slide item
  flutter_slidable: "^0.5.4"
#  launch call like intent
  url_launcher: ^5.4.10
#  google map
  google_maps_flutter: ^0.5.28+1
  google_maps_webservice: ^0.0.17
  flutter_google_places: ^0.2.5
  geolocator: ^5.3.2+2
  location: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/background.png
    - images/red_logo.png
    - images/white_logo.png
    - images/splash_bottom.png
    - images/splash_top.png
    - images/slide1.png
    - images/slide2.png
    - images/slide3.png
    - images/blood_drop.png
    - images/facebook.png
    - images/instagram.png
    - images/twitter.png
    - images/youtube.png
    - images/warning.svg

  # example:
  fonts:
    - family: shekari
      fonts:
        - asset: fonts/shekari.ttf
          style: italic

    - family: cairo
      fonts:
        - asset: fonts/cairo.ttf

  #    - family: RobotoMono
#      fonts:
#        - asset: fonts/RobotoMono-Regular.ttf
#        - asset: fonts/RobotoMono-Bold.ttf
#          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
